version: '3.1'

services:
  spring-cloud-config-server:
    image: hyness/spring-cloud-config-server
    restart: always
    ports:
      - 8888:8888
    environment:
      SPRING_APPLICATION_NAME: cloud-config server
      SPRING_CLOUD_CONFIG_SERVER_GIT_URI: $GIT_URI
      SPRING_CLOUD_CONFIG_SERVER_GIT_USERNAME: $GIT_USERNAME
      SPRING_CLOUD_CONFIG_SERVER_GIT_PASSWORD: $GIT_PASSWORD
      SPRING_CLOUD_CONFIG_SERVER_GIT_DEFAULT_LABEL: main
      SPRING_CLOUD_CONFIG_SERVER_GIT_SEARCH_PATHS: demo
  postgresql:
    image: postgres:16
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
